"""Spotting phishing links with machine learning, from scratch (chapter 14.2).

A URL shortener is a favourite tool for hiding phishing links, so real
shorteners check every link people create. This module trains a tiny
classifier (logistic regression, written with NumPy so nothing is hidden)
to score URLs as safe or suspicious.

The data is SYNTHETIC: generated by `make_dataset` from patterns that real
phishing links often show, plus deliberate noise. It's for learning the
method. A real system would train on real reported links (e.g. from phishing
feeds and user reports) and combine the model with blocklists and rules.

    uv run python -m snipai.abuse
"""

from __future__ import annotations

import random
import re
import zlib
from dataclasses import dataclass, field
from urllib.parse import urlsplit

import numpy as np
from numpy.typing import NDArray

Floats = NDArray[np.float64]

# ---------------------------------------------------------------------------
# 1. Data: labelled examples (1 = phishing, 0 = safe)
# ---------------------------------------------------------------------------

SAFE_HOSTS = [
    "go.dev", "www.python.org", "docs.python.org", "en.wikipedia.org", "github.com",
    "stackoverflow.com", "www.bbc.co.uk", "news.ycombinator.com", "arxiv.org",
    "developer.mozilla.org", "kubernetes.io", "www.postgresql.org", "www.youtube.com",
    "blog.example.org", "shop.example.com", "www.example.net",
]  # fmt: skip
SAFE_PATHS = [
    "/", "/doc/", "/wiki/Hash_table", "/questions/11227809", "/watch?v=dQw4w9WgXcQ",
    "/news/technology-123456", "/abs/1706.03762", "/docs/concepts/", "/blog/2026/09/release",
    "/en-US/docs/Web/HTTP", "/login", "/account/settings", "/about", "/pricing",
    "/search?q=url+shortener", "/downloads/", "/item?id=41234567",
]  # fmt: skip
# Small, legitimate websites (made up): hyphens and plain names are normal.
SMALL_SITES = [
    "sunny-bakery.com", "city-council.example.org", "my-portfolio.dev", "green-garden.shop",
]  # fmt: skip
# Made-up brands: phishing pages imitate well-known names.
BRANDS = ["examplebank", "megamail", "shopzone", "cloudbox", "paynow"]
BAIT_WORDS = ["login", "verify", "secure", "account", "update", "confirm", "wallet", "unlock"]
CHEAP_TLDS = ["top", "xyz", "support", "click", "info", "live"]
DOC_IPS = ["192.0.2.", "198.51.100.", "203.0.113."]  # reserved for documentation


def _phishing_url(rng: random.Random) -> str:
    brand, bait = rng.choice(BRANDS), rng.choice(BAIT_WORDS)
    tld = rng.choice(CHEAP_TLDS)
    ip = rng.choice(DOC_IPS) + str(rng.randint(1, 254))
    token = "".join(rng.choices("abcdef0123456789", k=rng.randint(8, 32)))
    return rng.choice(
        [
            f"http://{brand}-{bait}-{rng.choice(BAIT_WORDS)}.{tld}/{bait}?session={token}",
            f"https://{bait}.{brand}.com.{rng.choice(['auth', 'id', 'sso'])}-check.{tld}/{token}",
            f"http://{ip}/{brand}/{bait}.php",
            f"https://{brand}.com@{ip}/{bait}",
            f"https://{brand}{rng.randint(1, 99)}.{tld}/{bait}",
            f"https://{brand}-{bait}.com/",
            # Looks harmless: a hacked small website quietly hosting a phishing
            # page. Nothing in the URL gives it away; you'd need to look at the page.
            f"https://{rng.choice(SMALL_SITES)}/wp-content/uploads/{token[:6]}/index.html",
        ]
    )


def _safe_url(rng: random.Random) -> str:
    token = "".join(rng.choices("abcdef0123456789", k=rng.randint(16, 32)))
    scheme = "http" if rng.random() < 0.1 else "https"  # some real sites still lack https
    host = rng.choice(SAFE_HOSTS + SMALL_SITES)
    path = rng.choice(
        SAFE_PATHS
        + [
            # Real sites use "suspicious" words and random tokens too.
            f"/file/d/{token}/view",
            f"/reset-password?token={token}",
            "/account/verify-email",
            "/wp-content/uploads/2026/09/menu.pdf",
        ]
    )
    return f"{scheme}://{host}{path}"


def make_dataset(
    n: int = 2000, phishing_share: float = 0.1, noise: float = 0.03, seed: int = 7
) -> tuple[list[str], NDArray[np.int64]]:
    """Generate n labelled URLs. `noise` flips that share of labels, like real
    data, where some reports are simply wrong."""
    rng = random.Random(seed)
    urls, labels = [], []
    for _ in range(n):
        bad = rng.random() < phishing_share
        urls.append(_phishing_url(rng) if bad else _safe_url(rng))
        labels.append(int(bad) ^ int(rng.random() < noise))
    return urls, np.array(labels, dtype=np.int64)


# ---------------------------------------------------------------------------
# 2. Features: turning a URL into numbers a model can weigh
# ---------------------------------------------------------------------------

FEATURE_NAMES = [
    "length / 100",
    "digits share",
    "host is an IP address",
    "has @ in the address",
    "dots in host",
    "hyphens in host",
    "bait words",
    "cheap top-level domain",
    "uses https",
    "has a long random token",
]


def features(url: str) -> Floats:
    """Hand-crafted features: things a human would look at."""
    parts = urlsplit(url)
    host = parts.hostname or ""
    lower = url.lower()
    return np.array(
        [
            len(url) / 100,
            sum(c.isdigit() for c in url) / max(len(url), 1),
            float(bool(re.fullmatch(r"[\d.]+", host))),
            float("@" in parts.netloc),
            host.count("."),
            host.count("-"),
            sum(word in lower for word in BAIT_WORDS),
            float(host.rsplit(".", 1)[-1] in CHEAP_TLDS),
            float(parts.scheme == "https"),
            float(bool(re.search(r"[0-9a-f]{16,}", lower))),
        ],
        dtype=np.float64,
    )


def ngram_features(url: str, dims: int = 4096) -> Floats:
    """Many tiny features instead: which 3-character pieces appear, hashed into
    `dims` buckets. Flexible, but easy to overfit on little data."""
    v = np.zeros(dims)
    s = url.lower()
    for i in range(len(s) - 2):
        v[zlib.crc32(s[i : i + 3].encode()) % dims] = 1.0  # crc32: stable across runs
    return v


# ---------------------------------------------------------------------------
# 3. The model: logistic regression, trained by gradient descent
# ---------------------------------------------------------------------------


def sigmoid(z: Floats) -> Floats:
    """Squash any number into 0..1, so the output reads as a probability."""
    return 1 / (1 + np.exp(-np.clip(z, -30, 30)))


@dataclass
class LogisticRegression:
    learning_rate: float = 0.5
    epochs: int = 500
    l2: float = 0.0  # regularisation: a penalty on large weights (fights overfitting)
    weights: Floats = field(default_factory=lambda: np.zeros(0))
    bias: float = 0.0
    losses: list[float] = field(default_factory=list)

    def fit(self, x: Floats, y: NDArray[np.int64]) -> LogisticRegression:
        n, d = x.shape
        self.weights, self.bias, self.losses = np.zeros(d), 0.0, []
        for _ in range(self.epochs):
            p = self.predict_proba(x)
            # Log loss: small when confident and right, huge when confident and wrong.
            eps = 1e-12
            loss = -np.mean(y * np.log(p + eps) + (1 - y) * np.log(1 - p + eps))
            self.losses.append(float(loss + self.l2 * np.sum(self.weights**2) / 2))
            # Gradient: which direction to nudge each weight to reduce the loss.
            error = p - y
            grad_w = x.T @ error / n + self.l2 * self.weights
            grad_b = float(np.mean(error))
            self.weights -= self.learning_rate * grad_w
            self.bias -= self.learning_rate * grad_b
        return self

    def predict_proba(self, x: Floats) -> Floats:
        return sigmoid(x @ self.weights + self.bias)

    def predict(self, x: Floats, threshold: float = 0.5) -> NDArray[np.int64]:
        return (self.predict_proba(x) >= threshold).astype(np.int64)


# ---------------------------------------------------------------------------
# 4. Honest measurement: held-out data and the right metrics
# ---------------------------------------------------------------------------


def train_test_split(
    n: int, test_share: float = 0.25, seed: int = 0
) -> tuple[NDArray[np.int64], NDArray[np.int64]]:
    """Shuffle indexes 0..n-1 and split them: the model never sees the test part."""
    idx = np.random.default_rng(seed).permutation(n)
    cut = int(n * (1 - test_share))
    return idx[:cut], idx[cut:]


@dataclass
class Scores:
    accuracy: float
    precision: float  # of the links we flagged, how many were really phishing?
    recall: float  # of the real phishing links, how many did we catch?
    tp: int
    fp: int
    fn: int
    tn: int

    def __str__(self) -> str:
        return (
            f"accuracy {self.accuracy:.1%}  precision {self.precision:.1%}  "
            f"recall {self.recall:.1%}  (caught {self.tp}, missed {self.fn}, "
            f"false alarms {self.fp}, correctly allowed {self.tn})"
        )


def score(y_true: NDArray[np.int64], y_pred: NDArray[np.int64]) -> Scores:
    tp = int(np.sum((y_pred == 1) & (y_true == 1)))
    fp = int(np.sum((y_pred == 1) & (y_true == 0)))
    fn = int(np.sum((y_pred == 0) & (y_true == 1)))
    tn = int(np.sum((y_pred == 0) & (y_true == 0)))
    return Scores(
        accuracy=(tp + tn) / len(y_true),
        precision=tp / (tp + fp) if tp + fp else 0.0,
        recall=tp / (tp + fn) if tp + fn else 0.0,
        tp=tp,
        fp=fp,
        fn=fn,
        tn=tn,
    )


def main() -> None:
    urls, y = make_dataset()
    train, test = train_test_split(len(urls))
    print(f"{len(urls)} URLs, {y.mean():.0%} labelled phishing;", end=" ")
    print(f"train {len(train)}, test {len(test)}")

    print("\n1. The lazy baseline: call everything safe")
    print("   test:", score(y[test], np.zeros(len(test), dtype=np.int64)))

    x = np.stack([features(u) for u in urls])
    model = LogisticRegression().fit(x[train], y[train])
    print("\n2. Logistic regression on 10 hand-made features")
    print(f"   loss: start {model.losses[0]:.3f} -> end {model.losses[-1]:.3f}")
    print("   train:", score(y[train], model.predict(x[train])))
    print("   test: ", score(y[test], model.predict(x[test])))
    print("   what it learned (weight per feature; + means 'more suspicious'):")
    for name, w in sorted(zip(FEATURE_NAMES, model.weights, strict=True), key=lambda t: -t[1]):
        print(f"     {w:+6.2f}  {name}")

    print("\n3. Choosing the threshold: a trade-off, not a fact")
    for t in (0.2, 0.5, 0.8):
        print(f"   threshold {t}:", score(y[test], model.predict(x[test], threshold=t)))

    # Overfitting: a flexible model with too little data memorises its examples.
    xn = np.stack([ngram_features(u) for u in urls])
    print("\n4. Flexible models need more data (4,096 character-trigram features)")
    print("   model                               train acc   test")
    for label, rows, feats, l2 in [
        ("10 hand-made features, 150 URLs", 150, x, 0.0),
        ("trigrams, 150 URLs", 150, xn, 0.0),
        ("trigrams, 300 URLs", 300, xn, 0.0),
        ("trigrams, 300 URLs, l2=0.003", 300, xn, 0.003),
        ("trigrams, all 1,500 URLs", 1500, xn, 0.0),
    ]:
        part = train[:rows]
        lr, epochs = (0.5, 500) if feats is x else (2.0, 3000)
        m = LogisticRegression(learning_rate=lr, epochs=epochs, l2=l2).fit(feats[part], y[part])
        train_acc = score(y[part], m.predict(feats[part])).accuracy
        print(f"   {label:<35} {train_acc:9.1%}   {score(y[test], m.predict(feats[test]))}")

    print("\n5. What the hand-feature model gets wrong (test URLs labelled phishing, scored < 50%)")
    p = model.predict_proba(x[test])
    for i, prob in zip(test, p, strict=True):
        if y[i] == 1 and prob < 0.5:
            print(f"   {prob:5.0%}  {urls[i]}")

    print("\nTry it:")
    for url in [
        "https://go.dev/doc/",
        "http://examplebank-verify-login.top/login?session=9f8e7d6c5b4a3f2e1d",
    ]:
        p = model.predict_proba(features(url)[None, :])[0]
        print(f"   {p:6.1%}  {url}")


if __name__ == "__main__":
    main()
